### DISCUSSION TITLE
Provide Means to Set Color of Entry Upon Hover

### DISCUSSION THREAD

**Discussion by PaltryProgrammer** [hluk/CopyQ#2687] [Ideas]
greetings kind regards
thank you for providing CopyQ i utilize it constantly . may i please request feature i.e. set color of my choosing of any entry upon mouse hover . 
thank you kindly

**Comment by hluk** [comment]
It should be possible to override by clicking on Edit Theme button in Appearance settings (by setting, for example `hover_item_css="background: red"`), but it was broken. Fixing in #2796.

Even without the fix, it is still possible to override this in the `items.css` style sheet installed with the app. See: https://copyq.readthedocs.io/en/latest/theme.html

You would need to append something like the following to the style sheet:

```css
#ClipboardBrowser::item:hover:selected{background:red}
#ClipboardBrowser::item:hover:!selected{background:red}
```
