### ISSUE TITLE
Allow changing CSS for the toolbar in the integrated editor

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1374]
I find the toolbar in the integrated editor very hard to see when using a dark background.  When the buttons are pressed, they become black just like the background.

Is there a way to use CSS to customize them?  If not, could this be added?

Note that I'm not referring to the main toolbar, for which editing the CSS is very easy thanks to your clever design.

**Comment by hluk** [comment]
You can try adding following to the stylesheets (e.g. `items.css`):

```css
#ClipboardBrowser QToolBar {
    background: black;
}
#ClipboardBrowser QToolBar QToolButton:hover {
    background: white;
}
#ClipboardBrowser QToolBar QToolButton:pressed {
    background: yellow;
}
```

(To quickly reload the css after editing, you can open and apply preferences from the main window - basically Ctrl+P and Enter.)

But the button icon color is calculated from the widget background.

The stylesheets require a lot of work to get right on various desktop environments and system themes.

See also Qt documentation:
- Examples: https://doc.qt.io/qt-5/stylesheet-examples.html
- Reference: https://doc.qt.io/qt-5/stylesheet-reference.html
