### ISSUE TITLE
Scrollbar too narrow for mouse

### ISSUE THREAD

**Issue by firstrose** [hluk/CopyQ#1754]
![copyq_fr](https://user-images.githubusercontent.com/1551595/132807885-f91289af-de2c-449e-86e9-53b95ad35a34.png)

A few versions ago, the scrollbar was wide. But in new versions, it's too narrow. It's hard to click on the scrollbar. 

Could you add option to set width of it?

**Comment by hluk** [comment]
Edit `themes/scrollbar.css` in your CopyQ installation and increase the value on lines:

```css
QScrollBar:horizontal {height:4px}
QScrollBar:vertical {width:4px}
```
